# Generated by Django 6.0.1 on 2026-01-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_user_restaurant_review",
        ),
    ]
